server:
  port: 8087

spring:
  application:
    name: user-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/teapack_kpi_db
    username: teapack
    password: teapack123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users

  flyway:
    enabled: true
    schemas: users
    locations: classpath:db/migration
    baseline-on-migrate: false
    default-schema: users

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000  # 24 часа в миллисекундах

logging:
  level:
    com.teapack.users: DEBUG