// Единый источник описаний KPI: используется в подсказках на дашборде/отчётах
// и на странице /help/kpi. При изменении формул в KpiCalculator — обновить здесь.

export const KPI_GROUPS = {
  BASE: 'Базовые KPI (по методике ОЕЕ)',
  TIME: 'Метрики времени',
  PERF: 'Метрики производительности',
  QUALITY: 'Метрики качества',
}

export const KPI_DESCRIPTIONS = {
  oee: {
    title: 'OEE — Overall Equipment Effectiveness',
    group: KPI_GROUPS.BASE,
    unit: '%',
    formula: 'OEE = Availability × Performance × Quality',
    desc: 'Интегральный показатель общей эффективности оборудования. Отражает потери по трём независимым осям: время (простои), скорость, качество.',
    interpretation: 'Эталонное значение «World class» — 85% (A=90%, P=95%, Q=99.9%). Для упаковочных линий нормой считают 60–75%.',
    higherIsBetter: true,
  },
  availability: {
    title: 'Availability — Доступность',
    group: KPI_GROUPS.BASE,
    unit: '%',
    formula: 'Availability = OperatingTime / PlannedTime\nOperatingTime = PlannedTime − Downtime',
    desc: 'Доля плановой смены, в течение которой оборудование фактически работало. Учитывает все простои (плановые и внеплановые).',
    interpretation: 'Падение Availability — повод смотреть журнал простоев и события STOP/START.',
    higherIsBetter: true,
  },
  performance: {
    title: 'Performance — Производительность',
    group: KPI_GROUPS.BASE,
    unit: '%',
    formula: 'Performance = TotalOutput / (NominalSpeed × OperatingTime)',
    desc: 'Отношение фактического выпуска к теоретическому максимуму на ВРЕМЕНИ РАБОТЫ (без простоев). Простои уже учтены в Availability — двойного штрафа нет.',
    interpretation: 'Падение Performance — оборудование работает медленнее номинала: микро-остановки, регулировки, сырьё низкого качества.',
    higherIsBetter: true,
  },
  quality: {
    title: 'Quality — Качество',
    group: KPI_GROUPS.BASE,
    unit: '%',
    formula: 'Quality = GoodOutput / TotalOutput',
    desc: 'Доля годной продукции в общем выпуске. Регистрируется через события SCRAP оператора.',
    interpretation: 'Падение Quality — нарушение спецификации, износ оборудования, ошибки наладки.',
    higherIsBetter: true,
  },
  plannedTime: {
    title: 'Planned Time — Плановое время',
    group: KPI_GROUPS.TIME,
    unit: 'мин',
    formula: 'PlannedTime = plannedEnd − plannedStart',
    desc: 'Длительность смены по плану в минутах. Берётся из карточки смены.',
    higherIsBetter: null,
  },
  operatingTime: {
    title: 'Operating Time — Время работы',
    group: KPI_GROUPS.TIME,
    unit: 'мин',
    formula: 'OperatingTime = PlannedTime − Downtime',
    desc: 'Чистое время, когда линия фактически работала.',
    higherIsBetter: true,
  },
  downtime: {
    title: 'Downtime — Простой',
    group: KPI_GROUPS.TIME,
    unit: 'мин',
    formula: 'Downtime = Σ длительностей всех событий STOP→START',
    desc: 'Суммарное время простоев за смену.',
    higherIsBetter: false,
  },
  downtimeRate: {
    title: 'Downtime Rate — Доля простоев',
    group: KPI_GROUPS.TIME,
    unit: '%',
    formula: 'DowntimeRate = Downtime / PlannedTime',
    desc: 'Доля плановой смены, потерянная на простои.',
    higherIsBetter: false,
  },
  numberOfStops: {
    title: 'Number of Stops — Количество остановок',
    group: KPI_GROUPS.TIME,
    unit: 'шт',
    formula: 'count(events.type = STOP)',
    desc: 'Сколько раз линия останавливалась за смену.',
    higherIsBetter: false,
  },
  avgDowntime: {
    title: 'Avg Downtime Duration — Средняя длительность остановки',
    group: KPI_GROUPS.TIME,
    unit: 'мин',
    formula: 'AvgDowntime = Downtime / NumberOfStops',
    desc: 'Среднее время одной остановки. Помогает отличить «много мелких» от «несколько долгих».',
    higherIsBetter: false,
  },
  outputRate: {
    title: 'Output Rate — Темп выпуска',
    group: KPI_GROUPS.PERF,
    unit: 'шт/мин',
    formula: 'OutputRate = TotalOutput / OperatingTime',
    desc: 'Фактический темп выпуска в штуках в минуту на работающее оборудование.',
    higherIsBetter: true,
  },
  speedLoss: {
    title: 'Speed Loss — Потери скорости',
    group: KPI_GROUPS.PERF,
    unit: 'шт/мин',
    formula: 'SpeedLoss = NominalSpeed − AvgSpeed',
    desc: 'Разница между номинальной и фактической средней скоростью линии.',
    higherIsBetter: false,
  },
  performanceLoss: {
    title: 'Performance Loss — Потери производительности',
    group: KPI_GROUPS.PERF,
    unit: '%',
    formula: 'PerformanceLoss = 1 − Performance',
    desc: 'Доля недополученного выпуска от теоретического максимума при работе оборудования.',
    higherIsBetter: false,
  },
  planFulfillment: {
    title: 'Plan Fulfillment — Выполнение плана',
    group: KPI_GROUPS.PERF,
    unit: '%',
    formula: 'PlanFulfillment = TotalOutput / PlannedOutput',
    desc: 'Отдельная от Performance метрика «насколько выполнен план по выпуску». Может превышать 100% (перевыполнение).',
    interpretation: 'Не путать с Performance: Performance считается на работающее время, PlanFulfillment — относительно планового объёма.',
    higherIsBetter: true,
  },
  scrapRate: {
    title: 'Scrap Rate — Доля брака',
    group: KPI_GROUPS.QUALITY,
    unit: '%',
    formula: 'ScrapRate = ScrapCount / TotalOutput',
    desc: 'Доля бракованной продукции от общего выпуска. Дополняет Quality (= 1 − ScrapRate).',
    higherIsBetter: false,
  },
}

export const getKpi = (key) => KPI_DESCRIPTIONS[key] || null
