server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: http://localhost:8087
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        - id: data-collection
          uri: http://localhost:8082
          predicates:
            - Path=/api/collect/**
          filters:
            - StripPrefix=0

        - id: data-processing
          uri: http://localhost:8083
          predicates:
            - Path=/api/shifts/**,/api/processing/**
          filters:
            - StripPrefix=0

        - id: kpi-calculation
          uri: http://localhost:8084
          predicates:
            - Path=/api/kpi/**
          filters:
            - StripPrefix=0

        - id: reporting
          uri: http://localhost:8085
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=0

        - id: notification
          uri: http://localhost:8086
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0

        - id: emulator
          uri: http://localhost:8081
          predicates:
            - Path=/api/emulator/**
          filters:
            - StripPrefix=0

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

logging:
  level:
    org.springframework.cloud.gateway: DEBUG